#! /bin/bash

git add .

msg="no message set"

if [ ! "$#" -gt 0 ]; then
	# msg=$1
	read -p 'Enter the commit message: ' msg

fi

if [ "$msg" eq "" ]; then
	echo "Message is required"
	exit
fi


git commit -am "$msg"

current=`git describe --tags --abbrev=0`
newversion="1.0.0"

if [ -f ".version" ]; then
	newversion="`cat .version`"
fi


if [ "$newversion" != "$current" ]; then
     git tag -a "$newversion" -m "`git log -1 --format=%s`"
     echo "Created a new tag, $newversion"
	 git push && git push --tags
else
	git push
fi
